Update README.md(データベース設計)
Stimulationparalysis/chat-space pull request #2
Opened 2019-04-27 08:00 UTC by Stimulationparalysis

- What
README.mdにchatSpaceのデータベース設計を記述した。
- Why
chatSpaceのデータベースを設計する為。

2019-04-27 08:04 UTC, yuki-uchida requested changes

2019-04-27 08:04 UTC, yuki-uchida commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
外部キー制約をつけたい場合にはrefference型としましょう

2019-04-27 08:04 UTC, yuki-uchida commented on README.md
> +|body|string|null: false|
メッセージかテキストのどちらかがあれば投稿できるようにしましょう

2019-04-27 11:48 UTC, Stimulationparalysis commented on README.md
> +|body|string|null: false|
ご指摘の内容は理解できますが、上記の内容をテーブルで表現する方法が分かりません。（自分なりに調べました）自分が実装するとしたら、JavaScriptでバリデーションをします。差し当たり、nullをtrueにしています。

2019-04-27 11:54 UTC, Stimulationparalysis commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
reference型を追加しました。

2019-04-27 12:10 UTC, Stimulationparalysis commented on README.md
> +|body|string|null: false|
ご指摘の内容は理解できますが、上記の内容をテーブルで表現する方法が分かりません。（自分なりに調べました）自分が実装するとしたら、JavaScriptでバリデーションをします。差し当たり、nullをtrueにしています。

2019-04-27 12:17 UTC, TOMARUMARU commented
integerをreferencesに変えましょう、という指摘ですね

2019-04-27 12:29 UTC, Stimulationparalysis commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
Type欄にreferencesを記述しました。

2019-04-27 12:31 UTC, Stimulationparalysis commented
> integerをreferencesに変えましょう、という指摘ですね
Type欄にreferencesを記述しました。

2019-04-27 12:37 UTC, TOMARUMARU commented on README.md
> +### Association
アソシエーションが間違ってます

2019-04-27 12:37 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|null: false|
不要ですね

2019-04-27 12:37 UTC, TOMARUMARU commented on README.md
> +|group_id|references|null: false, foreign_key: true|
こちらも

2019-04-27 12:37 UTC, TOMARUMARU commented on README.md
> +|groupName|string|index: true, null: false, unique: true|
nameで大丈夫です

2019-04-27 12:37 UTC, TOMARUMARU commented on README.md
> +|chatMember|string|null: false|
不要です

2019-04-27 12:37 UTC, TOMARUMARU commented on README.md
> +|group_id|integer|null: false|
不要です

2019-04-27 12:37 UTC, TOMARUMARU commented on README.md
> +|user_id|references|null: false, foreign_key: true|
不要です

2019-04-27 12:37 UTC, TOMARUMARU commented on README.md
> +### Association
messagesとも組みましょう

2019-04-27 12:52 UTC, Stimulationparalysis commented on README.md
> +### Association
修正しました。

2019-04-27 12:52 UTC, Stimulationparalysis commented on README.md
> +### Association
修正しました。

2019-04-27 12:52 UTC, Stimulationparalysis commented on README.md
> +|user_id|integer|null: false|
削除しました。

2019-04-27 12:52 UTC, Stimulationparalysis commented on README.md
> +|group_id|references|null: false, foreign_key: true|
削除しました。

2019-04-27 12:52 UTC, Stimulationparalysis commented on README.md
> +|groupName|string|index: true, null: false, unique: true|
変更しました。

2019-04-27 12:52 UTC, Stimulationparalysis commented on README.md
> +|chatMember|string|null: false|
削除しました。

2019-04-27 12:52 UTC, Stimulationparalysis commented on README.md
> +|group_id|integer|null: false|
削除しました。

2019-04-27 12:53 UTC, Stimulationparalysis commented on README.md
> +|user_id|references|null: false, foreign_key: true|
削除しました。

2019-04-27 12:53 UTC, Stimulationparalysis commented on README.md
> +### Association
追加しました。

2019-04-27 12:57 UTC, TOMARUMARU reviewed
messagesとgroupsのアソシエーションが間違ってます。
もう一度よく考えて修正をお願いします

2019-04-27 14:45 UTC, Stimulationparalysis commented
> messagesとgroupsのアソシエーションが間違ってます。
> もう一度よく考えて修正をお願いします

修正しました。

2019-04-28 02:06 UTC, ghost approved these changes
LGTMです！

2019-04-30 04:54 UTC, merged